<?php require 'header.php'; ?>

<div class="blog-content mt-4">
  <img src="img/blog.png" alt="foto karya brian donnelly di candi prambanan" class="blog-image">
  <h1>Brian Donnelly, dari Graffiti hingga Patung Jumbo di Candi Prambanan</h1>
  <p>Candi Prambanan kedatangan tamu baru tahun ini. Sebuah patung merah muda sepanjang 45 meter dengan tinggi 15 meter rebah dengan menutup wajahnya. Ini adalah patung bernama ‘ACCOMPLICE’ karya Brian Donnelly alias KAWS yang hadir di Candi Prambanan, Yogyakarta, dari 19 hingga 31 Agustus 2023. Advertisement: 1:51 Close Player Candi peninggalan Kerajaan Mataram Kuno tersebut menjadi satu dari sekian banyak lokasi tur pameran keliling dunia KAWS: HOLIDAY. Dan ini adalah kali pertama KAWS tampil di Situs Warisan Dunia UNESCO.</p>
  <p>KAWS bekerja sama dengan kolaborator lamanya, AllRightsReserved, untuk membawa ACCOMPLICE ke candi Hindu terbesar di Indonesia. Salah satu direksi AKG Entertainment, Axton Salim, bilang warna merah muda sengaja dipilih oleh tim AllRightsReserved dan AKG Entertainment selaku rekanan lokal. “Patung monumen seperti ini, warna pink yang disukai tentunya menjadi kontras. Warna ini sudah pernah dipakai di karya sebelumnya. Tapi untuk saya, itu terlihat bagus dengan warna hijau dan hitam milik candi,” katanya dilansir Detikcom beberapa waktu lalu. Lalu, Donnelly mengatakan sudah menyukai warna merah muda sejak lama. “Warna ini memang sangat perempuan sekali dan sebenarnya patung ini sudah pernah ditampilkan di pada 2002,” katanya.</p>
  <p>Pameran Kaws:Holiday Indonesia di Candi Prambanan (ANTARA FOTO/Andreas Fitri Atmoko/foc.) Gelombang Graffiti Tengkorak dari New Jersey hingga New York Karya seni Donnelly telah menawan hati berbagai kalangan. Mulai dari model Amerika Serikat Kylie Jenner, seniman pop art Andy Warhol, hingga pengusaha Israel kolektor seni Mugrabi. BACA JUGA Gandeng UNESCO, Kementerian PUPR Bangun Museum di Candi Borobudur Riset KIC: Masyarakat Dukung Kebijakan Larangan Naik Candi Borobudur Erick Thohir: BUMN Seimbangkan Sejarah dan Spiritual Candi Borobudur Lelaki asal Amerika Serikat tersebut juga sudah bekerja sama dengan label kelas atas Dior hingga ritel pakaian asal Jepang, Uniqlo. Kurator seni Simon Maidment bahkan menyebut KAWS sebagai fenomena budaya global. Mendunianya KAWS dengan ciri khas tengkorak dan tulang bersilang ini berakar dari seni graffiti.</p>
  <p>Jauh sebelum mencipta karakter layaknya di Candi Prambanan, Brian Donnelly dulunya seniman graffiti yang berkarya di bangunan sekitar tempat tinggalnya, Jersey City. Advertisement The Guardian mencatat Donnelly sudah mulai berkeliaran di kawasan itu sejak umur 12 tahun. Melalui hobinya berpapan luncur alias skateboard, ia menemukan komunitas seniman jalanan New York. “Kebanyakan mentornya adalah lelaki yang lebih tua, seperti Futura, Zephyr, dan Lee Quinones,” tulis The Guardian. ADVERTISEMENT Donnelly dapat sering melancong ke New York karena kakeknya bekerja di Port Authority Trans-Hudson (PATH) Trains. Ini adalah perusahaan yang mengoperasikan kereta cepat di New Jersey hingga New York City. Bersama mereka akan berjalan-jalan ke Manhattan hingga New York. Nama KAWS sudah tercipta di era graffiti Donnelly.</p>
  <p>Ia mengaku tidak ada arti khusus dari empat huruf ini tapi Donnelly yang masih berusia 12 tahun suka bagaimana keempat huruf itu terlihat dalam karyanya. Pria yang lahir pada 1974 ini kemudian menggunakan KAWS sebagai moniker dalam karya seninya. Awal 1990-an, Donnelly mulai serius di bidang seni dengan memegang gelar Bachelor of Fine Arts dari School of Visual Arts, New York City. Lelaki ini sempat bekerja sebagai seniman lepas alias freelance di Disney. Karyanya meliputi latar belakang animasi untuk 101 Dalmations, Daria, dan Doug. Berbeda dengan seniman lain yang dikenal lewat pameran seni, KAWS mulai dikenal berkat keisengan Donnelly. Ia akan mengambil iklan-iklan jenama besar di kota, menimpanya dengan tengkorak ala Donelly, dan mengembalikan ke tempat semula. Jenama yang menjadi 'korban' Donnelly misalnya Calvin Klein, Marlboro, dan Guess. “Ini adalah bukti eksistensi. Saya menyukai gambar iklan itu, saya melukisnya karena gambar itu ada di mana-mana,” kata Donnelly dilansir dari The Guardian. Akhirnya karya ‘bajakan’ ini ditampilkan di National Gallery of Victoria, Australia. Dari sana, Donnelly kian terkenal dan iklan graffitinya ini mulai dilirik berbagai kalangan.</p>
</div>

<?php require 'footer.php'; ?>